### ISSUE TITLE
MongoDB issue

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/slrise#11]
From Greg's email:

"I just installed a new VM and decided to setup EnTK from scratch.  All goes well until it comes time to register and connect to a mongodb service.  The one you use in your tutorial (mlabs.com) is no longer accepting new user accounts.  mLab is now part of MongoDB Atlas.  So I created an account, set up a free tier cluster, and associated a user with the database.

The problem comes in connecting to the database.  I get the connection string for the python driver, assign it to RADICAL_PILOT_DBURL, and run the "get_started.py" sample script."

**Comment by mturilli** [comment]
Hi Greg, unfortunately mlab interface has changed and it is now difficult/impossible to use with RCT. I created a DB for you on one of our machines. I will share the endpoint and login details privately.

**Comment by ggg121** [comment]
Thanks Matteo!  I tried the DB you provided seems to have done the trick and the "get_started.py" example runs.  The only hiccup (if it really is at all) is that, when closing the pilot manager, the process times out.  I ran the script three times and this occurs during each run.

**Comment by mturilli** [comment]
The hiccup you experienced is a known issue with RP. I am afraid it will not be fixed any time soon as it requires a full rewriting of part of the system. Nonetheless, this should not affect your executions.
