### ISSUE TITLE
Remove data from sub-model modules

### ISSUE THREAD

**Issue by ggg121** [radical-collaboration/slrise#13]
Remove the data files from the sub-model modules.  Must keep github happy!

**Comment by ggg121** [comment]
Removed data files from kopp14 icesheets and kopp14 thermalexpansion.  Committed changes to the branch and now waiting for pull request approval.

**Comment by ggg121** [comment]
It appears as though the data files still exist in the history of the repo.  When cloning the repo, hundreds of MB worth of data are downloaded...and the scripts definitely shouldn't take up that much space.  How do we entirely remove these files from the repo?

**Comment by mturilli** [comment]
Yes, they do remain in the history. Once we are ready to merge we will use the approach documented here: https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

**Comment by ggg121** [comment]
I followed the instructions in the link you sent using BFG to remove the history of the data files.  It looks like it was able to clean things up.  Go ahead and remove any cloned instances of this repo you may currently have and re-clone the repo.

**Comment by ggg121** [comment]
Data removed and branch merged.
