### ISSUE TITLE
Create initial pipeline with placeholders for tasks from the 4 stages

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/slrise#2]

**Comment by vivek-bala** [comment]
Apologies on the delay. I have a draft script at https://github.com/radical-collaboration/slrise/tree/master/prior_workflow/entk. This creates the kopp workflow with the calibration stage alone for now. As the other stages/tasks are ready we can add them to the Python and YAML scripts.

**Comment by ggg121** [comment]
Initial pipeline done.  Thanks Vivek!
